// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXpXX_kfz3ePhUROh8IJeWdkoF0QJrOCY',
    appId: '1:833416523526:web:52daf689f64ec5a61b7887',
    messagingSenderId: '833416523526',
    projectId: 'postit-45ed9',
    authDomain: 'postit-45ed9.firebaseapp.com',
    storageBucket: 'postit-45ed9.appspot.com',
    measurementId: 'G-8TGRLKF2RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaGnW8_Dvw_woGiRw_IcYdRXe1XyJD2NI',
    appId: '1:833416523526:android:36ef795d12e24d241b7887',
    messagingSenderId: '833416523526',
    projectId: 'postit-45ed9',
    storageBucket: 'postit-45ed9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxQvqEjvcWoz8bcc5ura38ODoJkkeijOg',
    appId: '1:833416523526:ios:97b26ad0bf4299251b7887',
    messagingSenderId: '833416523526',
    projectId: 'postit-45ed9',
    storageBucket: 'postit-45ed9.appspot.com',
    iosBundleId: 'com.example.postit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxQvqEjvcWoz8bcc5ura38ODoJkkeijOg',
    appId: '1:833416523526:ios:2d3c00da88db17221b7887',
    messagingSenderId: '833416523526',
    projectId: 'postit-45ed9',
    storageBucket: 'postit-45ed9.appspot.com',
    iosBundleId: 'com.example.postit.RunnerTests',
  );
}
